services:
    onfly.redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'onfly-redis:/data'
        networks:
            - onfly
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    onfly.postgres:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE:-api}'
            POSTGRES_USER: '${DB_USERNAME:-api}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'onfly-postgres:/var/lib/postgresql/data'
            - './api/docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh'
        networks:
            - onfly
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-api}"]
            retries: 3
            timeout: 5s

    node:
        image: node:23-alpine
        environment:
            NODE_ENV: development
        volumes:
            - ./site:/opt/apps/www
        working_dir: /opt/apps/www
        command: npm install --legacy-peer-deps
        
    composer:
        image: composer:2
        command: ["composer", "install", "--ignore-platform-reqs"]
        working_dir: /api
        volumes:
            - './api:/api'

networks:
    onfly:

volumes:
    onfly-postgres:
    onfly-redis:
